Sending OPTIONS request to API
opstalent/redux-crud pull request #3
Opened 2017-10-11 13:06 UTC by patgrudniewski

2017-10-11 14:33 UTC, patgrudniewski commented on tests/reducer.test.js
> +	const action = { type, payload };
@Druzzdil fix indentation here

2017-10-11 14:34 UTC, patgrudniewski commented on src/Loader.js
> +    Loader,
@Druzzdil indent

2017-10-12 07:48 UTC, auamarto requested changes

2017-10-12 07:48 UTC, auamarto commented on docs/api/README.md
> +> The crud reducer. Have to be mounted to Redux store at `crud`.
should be at `crud` what ?

2017-10-12 07:48 UTC, auamarto commented on src/reducer.js
> +export default reducer;
new line

2017-10-12 07:48 UTC, auamarto commented on tests/Loader.test.js
> +Enzyme.configure({ adapter: new Adapter() });
separate imports ?

2017-10-12 09:43 UTC, auamarto approved these changes

2017-10-12 09:43 UTC, merged